package gals;

import br.univali.Douglas_Daniel.Leitor;

public interface ScannerConstants
{
    int[][] SCANNER_TABLE = new Leitor().RetornaMatriz("tabela.txt");
    int[] TOKEN_STATE = { -1,   0,   0,  -1,  17,  45,  -1,   7,   8,  15,  13,  11,  14,  16,  57,  37,  12,  52,  18,  54,  44,   9,  10,  48,  44,  44,  41,  44,  44,  44,  44,  44,  44,  44,  44,  44,   5,  46,   6,  47,  -1,  60,  -1,  -1,  -1,   3,  -1,  49,  51,  55,  53,  50,  44,  44,  44,  44,  44,  44,  44,  44,  44,  44,  42,  44,  44,  44,  32,  44,  -1,  59,  19,  -1,  58,  44,  44,  44,  44,  44,  44,  44,  44,  44,  44,  44,  44,  44,  43,  44,  44,  44,  44,  44,  44,  60,   4,  44,  44,  44,  35,  44,  44,  44,  38,  44,  44,  44,  44,  44,  40,  36,  44,  27,  44,  44,  44,  44,  44,  44,  22,  44,  44,  31,  44,  44,  44,  44,  44,  44,  33,  44,  44,  29,  44,  44,  44,  21,  24,  44,  30,  44,  44,  44,  44,  44,  44,  34,  26,  44,  23,  44,  44,  28,  39,  20,  44,  44,  44,  25 };

    String[] SCANNER_ERROR =
    {
        "Caractere não esperado",
        "",
        "",
        "Erro identificando VALOR_CADEIA",
        "",
        "",
        "Erro identificando VALOR_CARACTER",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando VALOR_CADEIA",
        "",
        "Erro identificando VALOR_CARACTER",
        "Erro identificando \"-->\"",
        "Erro identificando COMENTARIO_VARIAS_LINHAS",
        "",
        "Erro identificando VALOR_REAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando VALOR_CADEIA",
        "",
        "",
        "Erro identificando COMENTARIO_VARIAS_LINHAS",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    };

}
